### ISSUE TITLE
build fail: about KeplerAs.pl  

### ISSUE THREAD

**Issue by kzjeef** [Jokeren/KeplerGEMM#1]
Hi Keren,

Do you know where can I find as for kepler, like KeplerAs.pl in your makefile ?

**Comment by Jokeren** [comment]
Hi @kzjeef ,

We had a Kepler Assembler, while my previous boss decided to make it private a few months ago. Here's his homepage, including his email through which you can contact:

http://www.ncic.ac.cn/~tgm/index.php/Main_Page

**Comment by kzjeef** [comment]
OK, Thanks for the information!
